"""Budget models for cost tracking, approval, and optimization."""
import enum
import uuid
from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    JSON,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column

from aeco.db.base import Base


class SpendCategory(str, enum.Enum):
    LLM_TOKENS = "llm_tokens"
    COMPUTE = "compute"
    API_CALLS = "api_calls"
    STORAGE = "storage"
    TOOLING = "tooling"
    OTHER = "other"


class ApprovalStatus(str, enum.Enum):
    AUTO_APPROVED = "auto_approved"
    APPROVED = "approved"
    DENIED = "denied"
    PENDING = "pending"
    ESCALATED = "escalated"


class AlertSeverity(str, enum.Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class BudgetPeriod(Base):
    """A budget allocation for a time period (e.g., monthly, per-project)."""

    __tablename__ = "budget_periods"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(String(200))
    scope: Mapped[str] = mapped_column(
        String(50), default="global"
    )  # "global", "project", "agent"
    scope_id: Mapped[Optional[str]] = mapped_column(
        String(200), index=True
    )  # project name or agent_id
    total_budget: Mapped[float] = mapped_column(Float, default=0.0)
    spent: Mapped[float] = mapped_column(Float, default=0.0)
    reserved: Mapped[float] = mapped_column(Float, default=0.0)  # pending approvals
    currency: Mapped[str] = mapped_column(String(10), default="USD")
    period_start: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    period_end: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    metadata_: Mapped[dict] = mapped_column("metadata", JSON, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    @property
    def remaining(self) -> float:
        return self.total_budget - self.spent - self.reserved

    @property
    def utilization_percent(self) -> float:
        if self.total_budget <= 0:
            return 0.0
        return (self.spent / self.total_budget) * 100


class SpendRecord(Base):
    """Individual spend event tied to an agent action."""

    __tablename__ = "spend_records"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    budget_period_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("budget_periods.id"), index=True
    )
    workflow_run_id: Mapped[Optional[uuid.UUID]] = mapped_column(index=True)
    task_id: Mapped[Optional[uuid.UUID]] = mapped_column(index=True)
    agent_id: Mapped[str] = mapped_column(String(100), index=True)
    category: Mapped[SpendCategory] = mapped_column(
        Enum(SpendCategory, values_callable=lambda e: [x.value for x in e]),
        default=SpendCategory.LLM_TOKENS,
    )
    amount: Mapped[float] = mapped_column(Float)
    description: Mapped[str] = mapped_column(Text, default="")
    approval_status: Mapped[ApprovalStatus] = mapped_column(
        Enum(ApprovalStatus, values_callable=lambda e: [x.value for x in e]),
        default=ApprovalStatus.AUTO_APPROVED,
    )
    approved_by: Mapped[Optional[str]] = mapped_column(String(100))
    tokens_used: Mapped[Optional[int]] = mapped_column(Integer)
    llm_model: Mapped[Optional[str]] = mapped_column(String(100))
    metadata_: Mapped[dict] = mapped_column("metadata", JSON, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )


class BudgetAlert(Base):
    """Alerts generated by the budget engine for anomalies and policy violations."""

    __tablename__ = "budget_alerts"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    budget_period_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("budget_periods.id"), index=True
    )
    alert_type: Mapped[str] = mapped_column(
        String(50)
    )  # "overspend", "anomaly", "trend", "policy_violation"
    severity: Mapped[AlertSeverity] = mapped_column(
        Enum(AlertSeverity, values_callable=lambda e: [x.value for x in e]),
        default=AlertSeverity.WARNING,
    )
    message: Mapped[str] = mapped_column(Text)
    agent_id: Mapped[Optional[str]] = mapped_column(String(100))
    workflow_run_id: Mapped[Optional[uuid.UUID]] = mapped_column()
    acknowledged: Mapped[bool] = mapped_column(Boolean, default=False)
    metadata_: Mapped[dict] = mapped_column("metadata", JSON, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
